---

  - name: gluster-cluster | Configure glusterfs peers
    shell:
      cmd: "gluster peer probe {{ item }}"
    register: glusterfs_peer_probe
    changed_when: "'already in peer list' not in glusterfs_peer_probe.stdout"
    delegate_to: "{{ glusterfs_nodes[0] }}"
    run_once: true
    become: true
    with_items: "{{ glusterfs_nodes }}"
    when: >
      item != glusterfs_nodes[0]
